### ISSUE TITLE
VPS

### ISSUE THREAD

**Issue by drtiwarir** [dhruv-2015/JIOTVServer#1]
**Is your feature request related to a problem? Please describe.**
=> No
description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
description of what you want to happen.
=> How to Install on VPS and use it 
I have VPS from AWS & Digital Ocean, if I install on any of the servers, how can I connect and watch on Android tv or Mac ? Can we generate m3u8 file and use it on devices at home ?

**Describe alternatives you've considered**
any alternative solutions or features you've considered.
=> No
**Additional context**
=> Can you please provide a detailed guide of setting it up on VPS

**Comment by dhruv-2015** [comment]
Join discord

**Comment by drtiwarir** [comment]
I have joined Discord, pasting my question there

**Comment by drtiwarir** [comment]
Dhruv, I have set it up on a VPS
It works well in kodi, but after 10-15 minutes I stopped it, then it sleeps, doesn’t work !
Even can’t login to http 
I redid sh start.sh, again starts working 
Something wrong with nodejs or pm2
Please help
Thanks

**Comment by drtiwarir** [comment]
Do I have to add cron job every 1-2 minutes ?

**Comment by dhruv-2015** [comment]
> Dhruv, I have set it up on a VPS It works well in kodi, but after 10-15 minutes I stopped it, then it sleeps, doesn’t work ! Even can’t login to http I redid sh start.sh, again starts working Something wrong with nodejs or pm2 Please help Thanks

You need to run server in background in order to use in kodi or any other app
You can use pm2 to run node server in background or use docker

**Comment by deepkharoud67** [comment]
Is there any way to set high quality by default ?
I am using iptv smarter pro.
Thanks

**Comment by dhruv-2015** [comment]
> Is there any way to set high quality by default ? I am using iptv smarter pro. Thanks

No its based on your internet speed

**Comment by drtiwarir** [comment]
I am not sure about IPTV smarter, but works in HD in Kodi
And should have at least 25 Mbps speed
