### ISSUE TITLE
Want to run it on Linux PC

### ISSUE THREAD

**Issue by sudo-Mystic** [dhruv-2015/JIOTVServer#2]
**Is your feature request related to a problem? Please describe.**
i dont have a spare phone to run it , but do have a pc linux (ubuntu based distro)

**Describe the solution you'd like**
tried running it but node module not seems to work on linux

**Describe alternatives you've considered**
dont have any

**Comment by bhanuagarwal73** [comment]
I guess you need to install the nodejs first
