### ISSUE TITLE
Playlist not working in Tivimate 

### ISSUE THREAD

**Issue by rehank3g** [dhruv-2015/JIOTVServer#7]
**Describe the bug**
Playlist not working in Tivimate.

**Expected behavior**
There are two types of video quality for each resolution one is working but other one is not working in Tivimate. Need to select the 
![Screenshot_2023-04-27-23-18-19-50_c4258fadb54036c5ffc2dcda5ee0e9e3](https://user-images.githubusercontent.com/56449037/234950269-912d2196-027f-41e9-a34a-b08e07037bb3.jpg)

**Comment by SP4RKiOP** [comment]
did you find any fix?

**Comment by rehank3g** [comment]
> did you find any fix?

Working in OTT navigator and m3uiptv player. Change the codec to exo
