### ISSUE TITLE
feat: More quality 

### ISSUE THREAD

**Issue by dhruvanbhalara** [dhruv-2015/JIOTVServer#8]
**Is your feature request related to a problem? Please describe.**
No 

**Describe the solution you'd like**
Add 1080p quality for streaming.

**Describe alternatives you've considered**

**Additional context**

**Comment by dhruv-2015** [comment]
720 is max by jio

**Comment by rrjanbiah** [comment]
@dhruv-2015 @dhruvanbhalara 

As far as I can see, TobAlan on Kodi shows many channels in 1080

**Comment by rrjanbiah** [comment]
> @dhruv-2015 @dhruvanbhalara
> 
> As far as I can see, TobAlan on Kodi shows many channels in 1080

@dhruv-2015 @dhruvanbhalara

Sorry, looks like I misunderstood. Now I see 720 even over there
