### ISSUE TITLE
Handler.js not found. 

### ISSUE THREAD

**Issue by jatinderpalsingh** [dhruv-2015/JIOTVServer#9]
I am executing this script on my windows laptop.
I have already installed nodejs.
Using start.bat in your package, I tried to run this script.
I got the error package 'express' and 'cors' are missing.
Using npm install commands, I have installed the packages
and
these package errors are gone.
again running start.bat, I am getting another error:
can not find module: JIOTVServer-main\build\handler.js' imported from JIOTVServer-main\index.js

There is no build folder in github repo and no handler.js file.
I checked index.js file and found that you are referring to handler.js on Line 18.
Kindly check and update the package.

**Comment by csetube** [comment]
Am also facing the same issue

**Comment by rrjanbiah** [comment]
@jatinderpalsingh  @csetube I can see the mentioned file and folder in https://github.com/dhruv-2015/JIOTVServer/tree/main/build and to the bug is now outdated?

**Comment by dhruv-2015** [comment]
It's fixed.
